
FROM arm64v8/node:22-slim

WORKDIR /app

COPY app/pages/out ./pages
COPY app/backend/dist ./dist
COPY app/backend/package.json backend/package-lock.json ./
COPY app/backend/.env.prod ./.env

ENV NODE_ENV=production

RUN npm ci --omit=dev --verbose

RUN apt-get update && apt-get install -y nginx openssh-server curl vim bash

ENV NEXT_TELEMETRY_DISABLE=1

COPY proxy/nginx.conf /etc/nginx/nginx.conf
COPY proxy/default.conf /etc/nginx/sites-available/default
RUN nginx -t

EXPOSE 22 80 2222

RUN chmod +x /app/*.sh

ENV RESOURCE_FOLDER=/mount_point
RUN mkdir -p "$RESOURCE_FOLDER"
VOLUME $RESOURCE_FOLDER

RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh
COPY ssh/root_access_rsa.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys

ENV HOSTNAME=0.0.0.0

CMD ["/bin/sh", "-c", "/app/sftp.sh admin proctor2024 && /app/launch_services.sh"]
